### ISSUE TITLE
[Bug]: Some windows are not sized properly

### ISSUE THREAD

**Issue by HanabishiRecca** [Bismuth-Forge/bismuth#102]
### Summary

Some windows are not sized properly to the tiles and appear bigger then they should.

### Steps to Reproduce

Just open e.g. default plasma "System Settings" app with some other windows.

### Expected behavior

Window should size properly.

### Screenshots

![image](https://user-images.githubusercontent.com/13597663/136797590-9c525224-6421-4384-ad42-4de54a814cb2.png)

![image](https://user-images.githubusercontent.com/13597663/136797688-cc3fd146-3c8c-46f2-87fc-b4d13e38f444.png)

### Bismuth version

1.0.1

### KDE Plasma version

5.22.5

### The platform KWin is running on

X11

**Comment by gikari** [comment]
This is because windows in KWin has their minimal size. If the KWin had an option to opt out of this behavior while the script is loaded, it would be the solution.

In the meantime you can work around this by [setting window rule](https://github.com/gikari/bismuth/blob/master/TWEAKS.md#setting-minimum-geometry-size).

**Comment by cpelley** [comment]
> This is because windows in KWin has their minimal size. If the KWin had an option to opt out of this behavior while the script is loaded, it would be the solution.
> 
> In the meantime you can work around this by [setting window rule](https://github.com/gikari/bismuth/blob/master/TWEAKS.md#setting-minimum-geometry-size).

Tweaks file now moved since this comment.  In case others come across this issue, the [docs](https://bismuth-forge.github.io/bismuth/) references the latest location for these tweaks.

Thank you for posting this workaround - exactly what I needed :)
I wonder whether it would be useful to pin this issue?

**Comment by doqfgc** [comment]
> Tweaks file now moved since this comment. In case others come across this issue, the [docs](https://bismuth-forge.github.io/bismuth/) references the latest location for these tweaks.

The docs now 404s when navigating to the location for those tweaks, so here's where I found them once again:
https://github.com/Bismuth-Forge/bismuth/blob/master/docs/TWEAKS.md

Probably should fix that; the docs website is missing several other pages and other items (such as the image with the "demo" title right under the top header).
