### ISSUE TITLE
[Bug]: Most of the utility windows are not floated in Wayland session

### ISSUE THREAD

**Issue by CarlosEkisde** [Bismuth-Forge/bismuth#115]
### Summary

When using bismuth on a wayland session, utility windows are tiled just like any other window. Even if the corresponding option at the configuration menu is marked.

### Steps to Reproduce

Just open a dialog window with bismuth enabled. If you use the classic menu launcher, submenues are also tiled.

### Expected behavior

Utility windows float

### Bismuth version

1.0.1

### KDE Plasma version

5.23.0

### The platform KWin is running on

Wayland

**Comment by pasqui23** [comment]
I can confirm that the app menu for gtk windows is tiled as shown in https://github.com/NixOS/nixpkgs/issues/145274

**Comment by KouAkitaki** [comment]
I've encountered the same issue when `git` prompts for credentials. The popup window gets tiled while it shouldn't.
![Screenshot_20211128_012403](https://user-images.githubusercontent.com/17219127/143725379-8977e6a0-17ed-4bad-87e9-817c5a6c5318.png)

* KDE Plasma 5.23.3 on Wayland
* Bismuth 2.1.0

**Comment by bpgerber** [comment]
Can also confirm.

Splash screens get tiled. Utility screens like password prompts get tiled and maximized to fill the tiled area, everything gets tiled.
![tiling_problem_1](https://user-images.githubusercontent.com/17035587/144128719-4fa506b6-c7f1-477a-8b08-645ab606210d.png)
![tiling_problem_2](https://user-images.githubusercontent.com/17035587/144128736-889c0e57-e7f6-4a04-a694-9dc820275e67.png)


    KDE Plasma 5.23.3 on Wayland
    Bismuth 2.1.0

**Comment by kouakitaki** [comment]
As of Bismuth 2.3.0 KDE Plasma 5.23.3, this bug is still present on Wayland sessions.

**Comment by TheMachine02** [comment]
It seems in order to partially solve this bug when need to use the .transient propriety per old comment of kwin developper
> There is no any straightforward way to determine window type on Wayland. If you want to figure out if a window is a dialog, you could check its transient parent, AbstractClient::transientFor().

However, this propriety lies in AbstractClient class which is a derivated class from TopLevel. As I understand, the script currently use TopLevel from kwin.client ? But my java script skill are a bit too poor to follow that.
(cf https://develop.kde.org/docs/extend/plasma/kwin/api/#kwintoplevel )

Not so sure how we could have an abstractClient class instead of a topLevel and then correctly check 
`(this.client.dialog || this.client.splash || this.client.utility || this.client.transient))` inside driver/windows.ts at line 132 (or even better, as I understand, only `this.client.transient` propriety)

@gikari , an idea to have this propriety exposed with an AbstractClient class for the this.client ? TopLevel are public inside AbstractClient btw.

**Comment by gikari** [comment]
@TheMachine02 `this.client` has the artificially defined type of `KWin.Client` (which means it's Client and not TopLevel) and  it is possible to use `transient` property for it. 

However, it is not defined in the `kwin.d.ts` file, so to be able to use it and pass the TypeScript check, you need to add it there.

If you're able to, you can check if it works and submit the PR.

**Comment by TheMachine02** [comment]
Oh perfect ! I'll try it.
