### ISSUE TITLE
[Bug]: kwin script not enabled upon install

### ISSUE THREAD

**Issue by vacy** [Bismuth-Forge/bismuth#179]
### Summary

installed bismuth 2.1.0 but in kwin scripts settings bismuth wasnt enabled, so nothing changed, i tracked .config with git for changes and found enabling bismuth in kwin scripts changed this setting:

`.config/kwinrc`

> [Plugins]
>-bismuthEnabled=false
>+bismuthEnabled=true

>  cat /etc/fedora-release 
> Fedora release 34 (Thirty Four)

Its working after manual activation

### Steps to Reproduce

download bismuth 2.1.0 and
>npm install # Installs dependencies for building
>npm run sysdep-install # Install system dependencies for building
>npm run bi-install # Installs all Bismuth components

output:

>🎉 Installation finished.
>💡 You can configure Bismuth in the System Settings > Window Management > Window Tiling.
> 🦾 Enjoy your tiling!

### Expected behavior

kwin script to be enabled by default

### Bismuth version

2.1.0

### KDE Plasma version

5.22.5

### The platform KWin is running on

X11

### Additional context

reported here already: https://www.reddit.com/r/kde/comments/qlvjl4/bismuth_an_advanced_kde_plasma_tiling_extension/hk1yauu/

**Comment by gikari** [comment]
I think enabling by default is not a good idea, since the script can throw the windows very randomly, and the user could "Oh WTF, I just installed something and the windows got wonky, I want to disable that, but how and where? Where is my setting window, what a weird layout, aaaaah *panic*". Instead, I created a checkbox in the setting, that is immediately presented to the user. Installation script also now prints you a message, that you can enable the tiling in the settings. The last would work only, if you're installing from sources, other methods of installation are the responsibility of packagers.

**Comment by verahawk** [comment]
What about calling `kcmshell5 kcm_bismuth` or `systemsettings5 kcm_bismuth` right at the end of the installation script?
