### ISSUE TITLE
[FEATURE]: Is there a way to donate to this project?

### ISSUE THREAD

**Issue by EPadronU** [Bismuth-Forge/bismuth#262]
### Summary

Is there a way to donate money to this project:
* to increase the chance of it to be maintained
* to be grateful for all the hard work it had been put into bismuth
* to be grateful for the workflow this project has made possible to achieve for me

### A clear and concise description of what you want to happen

A way to contribute to the project and keep it alive with a monetary donation.

**Comment by niksingh710** [comment]
yes with a telegram or discord group too for comunication.

**Comment by gikari** [comment]
Thank you for your support!

As for the Donation page - there is currently none. It is unlikely, that there will be any in the near future, because I am not sure how to set up the system for the whole project.

However, I've just created a personal donation page at https://ko-fi.com/gikari.

You may also consider [donating to KDE](https://kde.org/community/donations/). Bismuth is based on the KDE technologies, so they deserve the praise, I think.

> yes with a telegram or discord group too for comunication.

I am not sure whether it's a good idea to create a group in general. I won't be able to answer all the questions here fast enough. Furthermore, I also do not have time to moderate it.

**Comment by gikari** [comment]
Ok, I discovered a decent service, that lets you collect donations for the project. It's LiberaPay and I created a team account for Bismuth. For now, the Bismuth team is only me. 

https://liberapay.com/bismuth/
