### ISSUE TITLE
[Bug]: Window Rules are not correctly applied since last update (Steam & Signal)

### ISSUE THREAD

**Issue by DarthSpot** [Bismuth-Forge/bismuth#329]
### Summary

i have had the same "window rules" every since i started using bismuth: Steam, discord and signal-desktop should be floating windows. Ever since the 

### Steps to Reproduce

1. Go to Window Tiling > Window Rules
2. Enter "discord,Steam,signal-desktop" for "Float Windows"
3. Apply

Steam and Signal are tiled. Discord is floating.

### Expected behavior

Steam, Discord and Signal to be started as floating windows

### Bismuth version

3.0.0-1 (AUR)

### KDE Plasma version

5.24

### The platform KWin is running on

X11

**Comment by ivangjxyz** [comment]
This bug is bigger than the title suggests. **Please consider prioritizing this bug**. It is affecting possibly the second biggest feature of Bismuth after _tiling windows_, which is, well... _floating windows_. 

And it is widespead. 

Here are some more windows where this is happening: 
- whatsapp-nativefier, whatsapp-nativefier-d40211, 
- kcalc, 
- megasync, 
- systemsettings5, systemsettings, 
- ark

So the problem is a lot more widespread. The only program I have found to still respect the floating rules is: 
- telegramdesktop

Also, in my case, this is happening on Arch Linux AUR package, but on **Wayland**.

I assume the issue is probably happening in the huge majority of windows, which is quite a mess.

**Comment by ivangjxyz** [comment]
As a temporary workaround, it seems that floating windows by _title_ still works fine. 

The thing is that, possibly if the window title changes dynamically, then it can be lottery.

**Comment by gikari** [comment]
Sterm works fine for. My rules for floating windows are: "steam,battle.net.exe,zotero,resolve" (there is no capital letter in "steam").

@ivangjxyz what are your window rules look like?

**Comment by b1scu1t** [comment]
Megasync, System Settings, SpeedCrunch, Steam and Pulseeffects all float as they should. However I must note that all the window classes are written in lower-case. Otherwise, the rule doesn't work at all. Also, Megasync's popup window aligns to the tray icon if it is 'ignored' by Bismuth (as it should).

Float window classes: "systemsettings,ktorrent,q4wine,krfb,discover,krdc,steam,skanpage,simplescreenrecorder,torbrowser-launcher,konversation,kget,plasma-systemmonitor,kinfocenter,diskmonitor,speedcrunch,khelpcenter,yast2,plasma.emojier,.exe,pulseeffects"

Ignore window classes: "yakuake,spectacle,Conky,megasync,lattedock".

![image](https://user-images.githubusercontent.com/41207956/161403908-abb06120-7007-440b-bfc9-8345fb1bf52e.png)

**Comment by ivangjxyz** [comment]
First of all, sorry for taking so long to answer. 

From your comments, I immediately came to the realisation, what has changed (or seems to have changed) from the previous Bismuth to v3.0 is that **spaces now break the floating rules**.

Because I (and probably also @DarthSpot) had rules setup like this,
```
signal, kcalc, whatever
```
and these were working totally fine until v3.0. 

# Solution

So, I have switched my rules to "no-space" separated comma list and everything works great again. 

# Suggestion

I suggest that spaces are allowed back into the rules, as it makes people not go crazy on why the rules are not working (and I am pretty sure spaces were allowed before v3.0); as it is a lot more easy to read for people, and also... I don't think window names with spaces are allowed anyway. 

---

In any case, people with this issue can just find the solution right here. Get rid of the bloaty spaces, people! :sweat_smile: 

Anyway, thank you for your work and your quick response time!

**Comment by ivangjxyz** [comment]
That was amazingly fast. Thanks!
