### ISSUE TITLE
[Bug]: Keyboard shortcuts are gone after updating to 3.1.0

### ISSUE THREAD

**Issue by jaburjak** [Bismuth-Forge/bismuth#343]
### Summary

After I upgraded bismuth to version 3.1.0 from 3.0.0, all keyboard shortcuts stopped working and all items under _Window Tiling_ in _System Settings_ show as _No active shortcuts_.

### Steps to Reproduce

1. Have custom keyboard shortcuts configured
2. Upgrade from 3.0.0 to 3.1.0

### Expected behavior

Shortcuts should keep working as before.

### Bismuth version

3.1.0

### KDE Plasma version

5.24.4

### The platform KWin is running on

Wayland

### Additional context

I got the same issue after upgrading from 2.3.0 to 3.0.0. Then I re-configured my keyboard shortcuts but now after upgrading to 3.1.0 they are gone again. Downgrading bismuth to 3.0.0 does not bring the previously configured shortcuts back.

The shortcuts seem to still be present in `~/.config/kglobalshortcutsrc` (see below), but they are not working and are not shown in the GUI.

```
[bismuth]
_k_friendly_name=Window Tiling
decrease_master_size=none,,Decrease Master Area Size
decrease_master_win_count=none,Meta+[,Decrease Master Area Window Count
...
```

**Comment by lucarillosi** [comment]
Same issue here, updated to 3.1.1 but shortcuts are still missing.

Content of `~/.config/kglobalshortcutsrc`
```
...
[bismuth]
_k_friendly_name=Window Tiling
decrease_master_size=none,,Decrease Master Area Size
decrease_master_win_count=none,Meta+[,Decrease Master Area Window Count
decrease_window_height=none,Meta+Ctrl+K,Decrease Window Height
decrease_window_width=none,Meta+Ctrl+H,Decrease Window Width
...
```

**Comment by gikari** [comment]
> Same issue here, updated to 3.1.1 but shortcuts are still missing.
> 
> Content of `~/.config/kglobalshortcutsrc`
> ```
> ...
> [bismuth]
> _k_friendly_name=Window Tiling
> decrease_master_size=none,,Decrease Master Area Size
> decrease_master_win_count=none,Meta+[,Decrease Master Area Window Count
> decrease_window_height=none,Meta+Ctrl+K,Decrease Window Height
> decrease_window_width=none,Meta+Ctrl+H,Decrease Window Width
> ...
> ```
>   

You won't be able to bring your shortcuts back if you were on 3.1.0 unfortunately, because migration script had a bug, that made it override the shortcuts unconditionally. 3.1.1 fixed it, but if the broken script already touched your shortcuts, you are out of luck.

You have to remap them manually again. Sorry for the inconvenience.

P.S. People upgrading from 2.x and 3.0.0 should be fine.

**Comment by jaburjak** [comment]
@lucarillosi I got my last note mixed up, as I didn’t really understand the contents of `kglobalshortcutsrc`. In each entry, the first item (before the first comma) seems to be the currently configured shortcut. Both our files have `none` in the first position, which means that the shortcuts got deleted after the upgrade to 3.1.0. I had to re-configure them manually.

**Comment by gikari** [comment]
Also, the script now overrides only empty shortcuts. So, it theoretically could rarely override the shortcut you have disabled. 

This is implemented like that, because KDE Global Shortcuts daemon is really weird and sometimes adds the empty entries. 

Once again, I really sorry about the breakages. This in general happened, because of number of factors, such as poorly documented behaviour of the kconf_update (KDE configuration migration tool), poorly documented and unintuitive behavior of KGlobalAccel (KDE Global Shortcuts daemon) and last, but not the least, my clumsiness.

**Comment by lucarillosi** [comment]
No problem, restoring the default shortcuts was a really simple point-and-click task, which took no more than a minute so.

By the way, thank you so much for maintaining bismuth. It really makes working with ultra-wide monitors soo much better :1st_place_medal:
