### ISSUE TITLE
[FEATURE]:  A simple kwin script variant?

### ISSUE THREAD

**Issue by techmouse** [Bismuth-Forge/bismuth#402]
### Summary

It would be nice to have a simple kwin script variant.

### A clear and concise description of what you want to happen

The installation instructions have outdated/broken links and don't explain what needs to be installed where. 

Even when it looks like everything has been properly installed manually, it still complains that kcm_bismuth can't be found.

Compiling it from source requires downloading hundreds of megs of dependencies, some via pip, and still gives non-specific generic pre-commit errors.

The only way I found to install it is with a .deb and that's an outdated 2.3.0 version.

A kwin script variant would simplify the installation process. It would make Bismuth easier to maintain, since it's a smaller project, and make Bismuth more portable, since kwin script installation should be the same across all distros.

Thank you.

**Comment by v3ss0n** [comment]
What do you mean? Stable versions are kiwin script

**Comment by gikari** [comment]
This is not possible, because we need KCM to be installed in a system directory.

I understand the need, but it's a general problem of Linux packaging. If there were a way to package Bismuth as a flatpak, I would have tried to create an official Flatpak package. This, however, is not possible.

If you have a problem with a concrete package, please contact the maintainer of that package.

**Comment by techmouse** [comment]
Help me understand. To use Bismuth, I'm supposed to either find a maintainer or become one myself?

**Comment by gikari** [comment]
> Help me understand. To use Bismuth, I'm supposed to either find a maintainer or become one myself?

To use Bismuth you could either:

1. Use a package from the community. The list of which is provided in the readme. Those packages are not provided by the developers of Bismuth, but from the 3rd party volunteers. It is their responsibility to make sure their package is installable and updated to the latest version.
2. Compile Bismuth manually. This is not a very user-friendly step, but it can be used if there is no package for your Linux distribution.

It is unfortunately a general delema of the software in Linux: packagers are separate from the developers. This is because there is a lot of Linux distributions and it is very costly for the developers to provide packages for every one of them.

This problem could be solved with a universal package format - Flatpak. But in case of Bismuth it is not applicable, because you can't properly package an extension for the existing software (in our case Plasma and KWin) in Flatpak.

Sorry, this most definitely suck for the user a.t.m., but we live in the imperfect world for now.

**Comment by v3ss0n** [comment]
With the C rewrite , it should be now able to write configuration right? Which current kwinscript limitation (QML) do not allow that.

**Comment by techmouse** [comment]
Well I'll just comment out the 'drag-to-float' block then.

By the way, how do I reference the mouse cursor's position in the script?
