### ISSUE TITLE
[Bug]: Bismuth is incompatible with new kwin version (5.26 beta)

### ISSUE THREAD

**Issue by HanabishiRecca** [Bismuth-Forge/bismuth#426]
### Summary

I just tried out Plasma 5.26 beta and seems like Bismuth is completely broken here. With Bismuth installed KWin just breaks and can't even render windows.
We probably want to make it compatible until the release.

### Steps to Reproduce

Try to use Plasma 5.26 beta with Bismuth.

### Expected behavior

Bismuth should work.

### Bismuth version

3.1.3

### KDE Plasma version

5.26

### The platform KWin is running on

X11

**Comment by gikari** [comment]
> can't even render windows.

Can you see the windows in task manager and move them via Right Click > More > Move?

**Comment by gikari** [comment]
I can confirm this bug. Bismuth works on kwin 5.25 and does not work on kwin 5.26 or master. I am currently trying to `git bisect` kwin changes, that broke Bismuth. This might take a long time, especially now, since I am in a process of moving my residence.

I recommend [submitting](https://bugs.kde.org/enter_bug.cgi?product=kwin) the bug report to KWin upstream. KWin Scripts should not break on KWin upgrade, unless they depend on the implementation.

**Comment by gikari** [comment]
I doubt, that KCM module is the reason of breakage. It has nothing to do with window management, and the code runs only when you have the settings window open. However, just to clarify, KCM is a fully supported thing. There is even a [tutorial](https://develop.kde.org/docs/extend/kcm/) on how to do it.

> I just tested old Krohnkite script and it works with 5.26. So yeah, this is definitely not a general scripts breakage.

It might be, that Bismuth uses some scripting functionality, that Krohnkite does not. I will try to find out what exactly.

**Comment by jkcdarunday** [comment]
Same experience. It looks to me that it's positioning the windows outside the screen. The minimize/maximize animation animates them as if they're positioned to the top left just outside the screen. Floating a window and then using the task bar's Right Click > More > Move functionality allows me to move it into view from the top left.

**Comment by cavillamizarc** [comment]
Hi!. This same issue happened to me since I upgraded to plasma 5.25. The windows seem to be positioned outside the screen. The way I got to make them appear again was by disabling the option "Prevent window from protruding from its screen". This makes the windows come back to my screen but they still don't tile properly.
I am using plasma 5.25.80 on Manjaro. Bismuth 3.1.3

**Comment by gikari** [comment]
> Hi!. This same issue happened to me since I upgraded to plasma 5.25. The windows seem to be positioned outside the screen. The way I got to make them appear again was by disabling the option "Prevent window from protruding from its screen". This makes the windows come back to my screen but they still don't tile properly.
> I am using plasma 5.25.80 on Manjaro. Bismuth 3.1.3
> 

Thanks, that will be useful. Btw, Plasma 5.25.80 is the same as 5.26. It's a convention in KDE to number betas like that.

**Comment by cavillamizarc** [comment]
> > Hi!. This same issue happened to me since I upgraded to plasma 5.25. The windows seem to be positioned outside the screen. The way I got to make them appear again was by disabling the option "Prevent window from protruding from its screen". This makes the windows come back to my screen but they still don't tile properly.
> > I am using plasma 5.25.80 on Manjaro. Bismuth 3.1.3
> 
> Thanks, that will be useful. Btw, Plasma 5.25.80 is the same as 5.26. It's a convention in KDE to number betas like that.


Thank you for the clarification! I didn't know that. Still, this happened to me before version 5.25.80. Can't really remember what version I installed. I didn't report it earlier because I thought it was just an issue on my side since I had other scripts runnning. I just disabled Bismuth until I had the time to check what went wrong. Btw, I'm using Wayland, if that's of any help

**Comment by gikari** [comment]
[This commit](https://invent.kde.org/plasma/kwin/-/commit/7292af3d0) in KWin breaks Bismuth. I need some more time to know why.

**Comment by gikari** [comment]
I found the reason of the bug. I was wrong, that Bismuth does not use C++ KWin API Wrappers on master branch. The usages were replaced with the standard JS KWin API to prevent breakages in the future. Everyone is welcome to test the #427 PR.

This is food for thought on how to actually use KWin API from C++, though.
